from __future__ import annotations

import base64
import hashlib
import json
import re
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd
import requests
from PIL import Image

try:
    RESAMPLE_LANCZOS = Image.Resampling.LANCZOS
except AttributeError:
    RESAMPLE_LANCZOS = Image.LANCZOS


# =========================
# Constants
# =========================

REQUIRED_INPUT_COLUMNS = [
    "Type",
    "sku",
    "template_no",
    "template_name",
    "image_url",
    "front_url",
    "angle_url",
    "side_url",
    "output_name",
    "note",
]

REQUIRED_TEMPLATE_COLUMNS = [
    "template_no",
    "template_name",
]

OPTIONAL_TEMPLATE_COLUMNS = [
    "template_display_name",
    "template_desc",
    "视觉特征",
    "qty_1_desc",
    "qty_2_desc",
    "qty_5_desc",
    "qty_10_desc",
    "qty_20_desc",
    "qty_30_desc",
    "image_1_url",
    "image_2_url",
    "image_5_url",
    "image_10_url",
    "image_20_url",
    "image_30_url",
]

REQUIRED_LAYOUT_COLUMNS = [
    "template_name",
    "quantity",
    "role",
    "pattern",
    "view",
    "count",
    "rows",
    "cols",
    "x1",
    "y1",
    "x2",
    "y2",
    "scale",
    "z_index",
    "note",
]

# Optional layout columns. If absent, defaults are applied.
OPTIONAL_LAYOUT_COLUMNS = [
    "enabled",
    "fit",
]

SUPPORTED_QUANTITIES = [2, 5, 10, 20, 30]

# New rule:
# - 1pcs is not generated by default.
# - Type=10 must generate 2/5/10 when layouts exist.
# - Type=30 must generate 2/5/10/20/30 when layouts exist.
# - 20/30 are skipped if the selected template has no matching layout.
TYPE_TO_QUANTITIES = {
    "10": [2, 5, 10],
    "30": [2, 5, 10, 20, 30],
}

VIEW_KEYS = ["image", "front", "angle", "side"]
SUPPORTED_PATTERNS = {
    "center",
    "matrix",
    "diagonal",
    "pyramid",
    "vertical",
    "horizontal",
    "manual",
}

DEFAULT_SCALE_CONFIG: Dict[str, Any] = {
    "global": {
        "sprite_canvas_size": 1000,
        "sprite_max_fill": 0.86,
        "render_scale": 1.00,
    },
    "templates": {},
}


# =========================
# Data models
# =========================

@dataclass
class Placement:
    view: str
    x: float
    y: float
    w: float
    h: float
    anchor: str = "center"
    scale: float = 1.0
    fit: str = "contain"


@dataclass
class LayoutRule:
    template_name: str
    quantity: int
    role: str
    pattern: str
    view: str
    count: int
    rows: int
    cols: int
    x1: float
    y1: float
    x2: float
    y2: float
    scale: float
    z_index: int
    fit: str = "contain"
    note: str = ""


# =========================
# Utility
# =========================

def deep_merge_dict(base: Dict[str, Any], override: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    result = json.loads(json.dumps(base))
    if not override:
        return result

    def merge(a: Dict[str, Any], b: Dict[str, Any]) -> Dict[str, Any]:
        for k, v in b.items():
            if isinstance(v, dict) and isinstance(a.get(k), dict):
                merge(a[k], v)
            else:
                a[k] = v
        return a

    return merge(result, override)


def get_scale_config(scale_config: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    return deep_merge_dict(DEFAULT_SCALE_CONFIG, scale_config)


def get_global_scale_value(scale_config: Optional[Dict[str, Any]], key: str, default: Any) -> Any:
    cfg = get_scale_config(scale_config)
    return cfg.get("global", {}).get(key, default)


def get_template_scale(template_name: str, scale_config: Optional[Dict[str, Any]] = None) -> float:
    cfg = get_scale_config(scale_config)
    tmpl = cfg.get("templates", {}).get(template_name, {})
    return float(tmpl.get("template_scale", 1.0))


def normalize_header(value: Any) -> str:
    return str(value).strip()


def clean_cell(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float) and pd.isna(value):
        return ""
    return str(value).strip()


def ensure_dir(path: str | Path) -> Path:
    p = Path(path)
    p.mkdir(parents=True, exist_ok=True)
    return p


def extract_sheet_id(sheet_url: str) -> str:
    m = re.search(r"/spreadsheets/d/([a-zA-Z0-9-_]+)", sheet_url)
    if not m:
        raise ValueError(f"Cannot extract Google Sheet ID from URL: {sheet_url}")
    return m.group(1)


def safe_filename(value: str) -> str:
    value = clean_cell(value)
    value = re.sub(r"[^\w\-\.]+", "-", value)
    value = re.sub(r"-+", "-", value).strip("-")
    return value or "unnamed"


def hash_url(url: str) -> str:
    return hashlib.md5(url.encode("utf-8")).hexdigest()[:16]


def parse_service_account_secret(secret_value: str) -> dict:
    """
    Supports:
    1. Raw JSON string
    2. Base64 encoded JSON string
    """
    secret_value = secret_value.strip()

    if secret_value.startswith("{"):
        return json.loads(secret_value)

    decoded = base64.b64decode(secret_value).decode("utf-8")
    return json.loads(decoded)


def normalize_template_key(value: Any) -> str:
    """Normalize template_no / Type values from Sheets, including 1.0 -> 1."""
    value = clean_cell(value)
    if not value:
        return ""
    if re.fullmatch(r"\d+\.0+", value):
        return value.split(".")[0]
    return value


def is_numeric_like(value: str) -> bool:
    value = clean_cell(value)
    return bool(re.fullmatch(r"\d+(?:\.0+)?", value))


def is_true_like(value: Any, default: bool = True) -> bool:
    v = clean_cell(value).lower()
    if not v:
        return default
    return v in {"true", "yes", "y", "1", "on", "enabled"}


def to_int(value: Any, field_name: str, default: Optional[int] = None) -> int:
    v = clean_cell(value)
    if not v:
        if default is not None:
            return default
        raise ValueError(f"{field_name} is required")
    try:
        return int(float(v))
    except Exception:
        raise ValueError(f"{field_name} must be integer-like, got: {value}")


def to_float(value: Any, field_name: str, default: Optional[float] = None) -> float:
    v = clean_cell(value)
    if not v:
        if default is not None:
            return default
        raise ValueError(f"{field_name} is required")
    try:
        return float(v)
    except Exception:
        raise ValueError(f"{field_name} must be number-like, got: {value}")


def validate_box(x1: float, y1: float, x2: float, y2: float, context: str) -> None:
    if not (0 <= x1 <= 1 and 0 <= x2 <= 1 and 0 <= y1 <= 1 and 0 <= y2 <= 1):
        raise ValueError(f"Layout coordinates must be between 0 and 1: {context}")
    if x2 <= x1 or y2 <= y1:
        raise ValueError(f"Invalid layout box, expected x2>x1 and y2>y1: {context}")


# =========================
# Google Sheet read
# =========================

def read_google_sheet_tabs(
    sheet_url: str,
    service_account_json_or_b64: str,
    input_tab: str,
    template_tab: str,
    layout_tab: str,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    import gspread
    from google.oauth2.service_account import Credentials

    scopes = [
        "https://www.googleapis.com/auth/spreadsheets.readonly",
        "https://www.googleapis.com/auth/drive.readonly",
    ]

    sa_info = parse_service_account_secret(service_account_json_or_b64)
    creds = Credentials.from_service_account_info(sa_info, scopes=scopes)
    client = gspread.authorize(creds)

    sheet_id = extract_sheet_id(sheet_url)
    sh = client.open_by_key(sheet_id)

    input_ws = sh.worksheet(input_tab)
    template_ws = sh.worksheet(template_tab)
    layout_ws = sh.worksheet(layout_tab)

    input_df = values_to_df(input_ws.get_all_values(), input_tab)
    template_df = values_to_df(template_ws.get_all_values(), template_tab)
    layout_df = values_to_df(layout_ws.get_all_values(), layout_tab)

    return input_df, template_df, layout_df


def values_to_df(values: List[List[str]], tab_name: str) -> pd.DataFrame:
    if not values:
        raise ValueError(f"Tab is empty: {tab_name}")

    # Find first non-empty row as header, allowing accidental leading blank rows.
    header_idx = None
    for i, row in enumerate(values):
        if "".join(str(x).strip() for x in row):
            header_idx = i
            break
    if header_idx is None:
        raise ValueError(f"Tab has no header row: {tab_name}")

    headers = [normalize_header(x) for x in values[header_idx]]
    rows = values[header_idx + 1 :]

    width = len(headers)
    normalized_rows = []
    for row in rows:
        row = row[:width] + [""] * max(0, width - len(row))
        normalized_rows.append(row)

    df = pd.DataFrame(normalized_rows, columns=headers)
    df = df.dropna(how="all")
    df = df.loc[~(df.astype(str).apply(lambda r: "".join(r).strip(), axis=1) == "")]
    return df


def validate_columns(df: pd.DataFrame, required_columns: List[str], tab_name: str) -> None:
    missing = [c for c in required_columns if c not in df.columns]
    if missing:
        raise ValueError(f"Missing columns in {tab_name}: {missing}")


# =========================
# Image download / preprocess
# =========================

def download_image(url: str, cache_dir: Path, timeout: int = 30) -> Path:
    url = clean_cell(url)
    if not url:
        raise ValueError("Empty image URL")

    ensure_dir(cache_dir)

    ext = ".jpg"
    clean_url_lower = url.split("?")[0].lower()
    if clean_url_lower.endswith(".png"):
        ext = ".png"
    elif clean_url_lower.endswith(".webp"):
        ext = ".webp"
    elif clean_url_lower.endswith(".jpeg"):
        ext = ".jpg"

    cache_path = cache_dir / f"{hash_url(url)}{ext}"

    if cache_path.exists() and cache_path.stat().st_size > 0:
        return cache_path

    headers = {"User-Agent": "Mozilla/5.0 bundle-image-generator/2.0"}
    resp = requests.get(url, headers=headers, timeout=timeout)
    resp.raise_for_status()

    cache_path.write_bytes(resp.content)
    return cache_path


def load_image_as_rgba(path: str | Path) -> Image.Image:
    img = Image.open(path)
    return img.convert("RGBA")


def remove_near_white_background(
    img: Image.Image,
    white_threshold: int = 246,
    alpha_softness: int = 10,
) -> Image.Image:
    img = img.convert("RGBA")
    pixels = img.load()
    w, h = img.size

    for y in range(h):
        for x in range(w):
            r, g, b, a = pixels[x, y]
            if a == 0:
                continue

            min_channel = min(r, g, b)

            if r >= white_threshold and g >= white_threshold and b >= white_threshold:
                pixels[x, y] = (r, g, b, 0)
            elif (
                r >= white_threshold - alpha_softness
                and g >= white_threshold - alpha_softness
                and b >= white_threshold - alpha_softness
            ):
                diff = 255 - min_channel
                new_alpha = max(0, min(a, diff * 18))
                pixels[x, y] = (r, g, b, new_alpha)

    return img


def crop_to_content(
    img: Image.Image,
    alpha_threshold: int = 10,
    padding: int = 8,
) -> Image.Image:
    img = img.convert("RGBA")
    alpha = img.getchannel("A")
    bbox = alpha.point(lambda px: 255 if px > alpha_threshold else 0).getbbox()

    if not bbox:
        return img

    left, top, right, bottom = bbox
    left = max(0, left - padding)
    top = max(0, top - padding)
    right = min(img.width, right + padding)
    bottom = min(img.height, bottom + padding)

    return img.crop((left, top, right, bottom))


def preprocess_product_image(
    img: Image.Image,
    remove_bg: bool = True,
    white_threshold: int = 246,
) -> Image.Image:
    img = img.convert("RGBA")
    if remove_bg:
        img = remove_near_white_background(img, white_threshold=white_threshold)
    img = crop_to_content(img)
    return img


def normalize_sprite_canvas(
    img: Image.Image,
    canvas_size: int = 1000,
    max_fill: float = 0.82,
) -> Image.Image:
    """
    Normalize every product source into the same transparent canvas.
    Layout filling should be tuned through Ref__BundleTemplateLayouts scale / box,
    and global render_scale if every image is globally too small.
    """
    img = img.convert("RGBA")

    if img.width <= 0 or img.height <= 0:
        raise ValueError("Invalid image size")

    max_side = int(canvas_size * max_fill)
    scale = min(max_side / img.width, max_side / img.height)

    new_w = max(1, int(img.width * scale))
    new_h = max(1, int(img.height * scale))

    resized = img.resize((new_w, new_h), RESAMPLE_LANCZOS)

    canvas = Image.new("RGBA", (canvas_size, canvas_size), (255, 255, 255, 0))
    x = int((canvas_size - new_w) / 2)
    y = int((canvas_size - new_h) / 2)
    canvas.alpha_composite(resized, (x, y))

    return canvas


def fit_image(
    img: Image.Image,
    target_w: int,
    target_h: int,
    fit: str = "contain",
) -> Image.Image:
    img = img.convert("RGBA")
    if img.width <= 0 or img.height <= 0:
        raise ValueError("Invalid image size")

    fit = clean_cell(fit).lower() or "contain"
    if fit not in {"contain", "cover"}:
        fit = "contain"

    if fit == "cover":
        scale = max(target_w / img.width, target_h / img.height)
    else:
        scale = min(target_w / img.width, target_h / img.height)

    new_w = max(1, int(img.width * scale))
    new_h = max(1, int(img.height * scale))
    resized = img.resize((new_w, new_h), RESAMPLE_LANCZOS)

    if fit == "cover":
        left = max(0, int((new_w - target_w) / 2))
        top = max(0, int((new_h - target_h) / 2))
        return resized.crop((left, top, left + target_w, top + target_h))

    return resized


def paste_center(
    canvas: Image.Image,
    img: Image.Image,
    cx: int,
    cy: int,
) -> None:
    x = int(cx - img.width / 2)
    y = int(cy - img.height / 2)
    canvas.alpha_composite(img, (x, y))


# =========================
# View resolution
# =========================

def resolve_url_map(row: pd.Series) -> Dict[str, str]:
    image_url = clean_cell(row.get("image_url", ""))
    front_url = clean_cell(row.get("front_url", ""))
    angle_url = clean_cell(row.get("angle_url", ""))
    side_url = clean_cell(row.get("side_url", ""))

    url_map = {
        "image": image_url,
        "front": front_url,
        "angle": angle_url,
        "side": side_url,
    }

    available = {k: v for k, v in url_map.items() if v}

    if not available:
        raise ValueError(f"No image URL found for sku={clean_cell(row.get('sku', ''))}")

    fallback_order = {
        "angle": ["angle", "front", "side", "image"],
        "front": ["front", "angle", "side", "image"],
        "side": ["side", "angle", "front", "image"],
        "image": ["image", "front", "angle", "side"],
    }

    resolved = {}
    for view, candidates in fallback_order.items():
        for c in candidates:
            if url_map.get(c):
                resolved[view] = url_map[c]
                break

    return resolved


def sprite_cache_path(
    sku: str,
    view: str,
    url: str,
    sprite_dir: Path,
) -> Path:
    """Stable sprite filename for debug/reuse."""
    ensure_dir(sprite_dir)
    sku_part = safe_filename(sku) or "sku"
    view_part = safe_filename(view) or "view"
    return sprite_dir / f"{sku_part}_{view_part}_{hash_url(url)}_sprite.png"


def build_view_images(
    url_map: Dict[str, str],
    cache_dir: Path,
    remove_bg: bool = True,
    white_threshold: int = 246,
    scale_config: Optional[Dict[str, Any]] = None,
    sku: str = "",
    sprite_dir: Optional[Path] = None,
    save_sprite_images: bool = False,
) -> Tuple[Dict[str, Image.Image], Dict[str, str], Dict[str, str]]:
    """
    Build normalized sprites for every view.

    Important:
    - cache_dir stores raw downloaded images.
    - sprite_dir stores processed product sprites.
    - Bundle rendering should use these normalized sprites, not raw images.
    """
    images: Dict[str, Image.Image] = {}
    source_paths: Dict[str, str] = {}
    sprite_paths: Dict[str, str] = {}

    sprite_canvas_size = int(get_global_scale_value(scale_config, "sprite_canvas_size", 1000))
    sprite_max_fill = float(get_global_scale_value(scale_config, "sprite_max_fill", 0.86))

    for view, url in url_map.items():
        raw_path = download_image(url, cache_dir=cache_dir)
        img = load_image_as_rgba(raw_path)
        img = preprocess_product_image(
            img,
            remove_bg=remove_bg,
            white_threshold=white_threshold,
        )
        img = normalize_sprite_canvas(
            img,
            canvas_size=sprite_canvas_size,
            max_fill=sprite_max_fill,
        )

        images[view] = img
        source_paths[view] = str(raw_path)

        if save_sprite_images and sprite_dir is not None:
            spath = sprite_cache_path(sku=sku, view=view, url=url, sprite_dir=sprite_dir)
            img.save(spath)
            sprite_paths[view] = str(spath)

    return images, source_paths, sprite_paths

# =========================
# Layout normalization
# =========================

def normalize_input_df(input_df: pd.DataFrame) -> pd.DataFrame:
    df = input_df.copy()
    df.columns = [normalize_header(c) for c in df.columns]
    validate_columns(df, REQUIRED_INPUT_COLUMNS, "Input__BundleImageURLs")

    for c in REQUIRED_INPUT_COLUMNS:
        df[c] = df[c].apply(clean_cell)

    df["Type"] = df["Type"].apply(normalize_template_key)
    df["template_no"] = df["template_no"].apply(normalize_template_key)

    if "enabled" in df.columns:
        df["enabled"] = df["enabled"].apply(lambda x: clean_cell(x).lower())
        df = df[df["enabled"].isin(["", "true", "yes", "y", "1", "on", "enabled"])].copy()

    df = df[df["sku"].astype(str).str.strip() != ""].copy()
    return df


def normalize_template_df(template_df: pd.DataFrame) -> pd.DataFrame:
    df = template_df.copy()
    df.columns = [normalize_header(c) for c in df.columns]
    validate_columns(df, REQUIRED_TEMPLATE_COLUMNS, "Ref__BundleTemplates")

    for c in REQUIRED_TEMPLATE_COLUMNS:
        df[c] = df[c].apply(clean_cell)

    df["template_no"] = df["template_no"].apply(normalize_template_key)

    for c in OPTIONAL_TEMPLATE_COLUMNS:
        if c in df.columns:
            df[c] = df[c].apply(clean_cell)

    # Drop accidental repeated header rows.
    df = df[
        ~(
            (df["template_no"].str.lower() == "template_no")
            | (df["template_name"].str.lower() == "template_name")
        )
    ].copy()

    df = df[df["template_name"].astype(str).str.strip() != ""].copy()
    return df


def normalize_layout_df(layout_df: pd.DataFrame) -> pd.DataFrame:
    df = layout_df.copy()
    df.columns = [normalize_header(c) for c in df.columns]
    validate_columns(df, REQUIRED_LAYOUT_COLUMNS, "Ref__BundleTemplateLayouts")

    for c in REQUIRED_LAYOUT_COLUMNS:
        df[c] = df[c].apply(clean_cell)

    if "enabled" not in df.columns:
        df["enabled"] = "TRUE"
    else:
        df["enabled"] = df["enabled"].apply(clean_cell)

    if "fit" not in df.columns:
        df["fit"] = "contain"
    else:
        df["fit"] = df["fit"].apply(clean_cell)
        df.loc[df["fit"] == "", "fit"] = "contain"

    # Drop accidental repeated header rows pasted into the body.
    df = df[
        ~(
            (df["template_name"].str.lower() == "template_name")
            | (df["quantity"].str.lower() == "quantity")
            | (df["role"].str.lower() == "role")
        )
    ].copy()

    # Drop blank rows.
    df = df[df["template_name"].astype(str).str.strip() != ""].copy()
    df = df[df["quantity"].astype(str).str.strip() != ""].copy()

    # Enabled filter.
    df = df[df["enabled"].apply(lambda x: is_true_like(x, default=True))].copy()

    df["quantity"] = df["quantity"].apply(lambda x: to_int(x, "quantity"))
    df["count"] = df["count"].apply(lambda x: to_int(x, "count", default=1))
    df["rows"] = df["rows"].apply(lambda x: to_int(x, "rows", default=1))
    df["cols"] = df["cols"].apply(lambda x: to_int(x, "cols", default=1))
    df["z_index"] = df["z_index"].apply(lambda x: to_int(x, "z_index", default=1))

    for c in ["x1", "y1", "x2", "y2"]:
        df[c] = df[c].apply(lambda x: to_float(x, c))
    df["scale"] = df["scale"].apply(lambda x: to_float(x, "scale", default=1.0))

    df["template_name"] = df["template_name"].apply(clean_cell)
    df["role"] = df["role"].apply(lambda x: clean_cell(x).lower())
    df["pattern"] = df["pattern"].apply(lambda x: clean_cell(x).lower() or "matrix")
    df["view"] = df["view"].apply(lambda x: clean_cell(x).lower() or "image")
    df["fit"] = df["fit"].apply(lambda x: clean_cell(x).lower() or "contain")

    for _, row in df.iterrows():
        context = f"template={row['template_name']}, quantity={row['quantity']}, role={row['role']}"
        validate_box(row["x1"], row["y1"], row["x2"], row["y2"], context)
        if row["count"] < 0:
            raise ValueError(f"count must be >= 0: {context}")
        if row["rows"] <= 0 or row["cols"] <= 0:
            raise ValueError(f"rows/cols must be positive: {context}")
        if row["view"] not in VIEW_KEYS:
            # Do not fail; view fallback happens later, but surface bad config strongly.
            raise ValueError(f"Unsupported view={row['view']} in {context}; supported: {VIEW_KEYS}")
        if row["pattern"] not in SUPPORTED_PATTERNS:
            raise ValueError(f"Unsupported pattern={row['pattern']} in {context}; supported: {sorted(SUPPORTED_PATTERNS)}")
        if row["fit"] not in {"contain", "cover"}:
            raise ValueError(f"Unsupported fit={row['fit']} in {context}; supported: contain/cover")

    return df


def build_layout_map(layout_df: pd.DataFrame) -> Dict[Tuple[str, int], List[LayoutRule]]:
    df = normalize_layout_df(layout_df)
    layout_map: Dict[Tuple[str, int], List[LayoutRule]] = {}

    for _, row in df.iterrows():
        rule = LayoutRule(
            template_name=clean_cell(row["template_name"]),
            quantity=int(row["quantity"]),
            role=clean_cell(row["role"]).lower(),
            pattern=clean_cell(row["pattern"]).lower(),
            view=clean_cell(row["view"]).lower(),
            count=int(row["count"]),
            rows=int(row["rows"]),
            cols=int(row["cols"]),
            x1=float(row["x1"]),
            y1=float(row["y1"]),
            x2=float(row["x2"]),
            y2=float(row["y2"]),
            scale=float(row["scale"]),
            z_index=int(row["z_index"]),
            fit=clean_cell(row.get("fit", "contain")).lower() or "contain",
            note=clean_cell(row.get("note", "")),
        )
        layout_map.setdefault((rule.template_name, rule.quantity), []).append(rule)

    for k in list(layout_map.keys()):
        layout_map[k] = sorted(layout_map[k], key=lambda r: r.z_index)

    return layout_map


# =========================
# Template / Type resolution
# =========================

def build_template_ref_maps(template_df: pd.DataFrame) -> Tuple[set[str], Dict[str, str]]:
    template_df = normalize_template_df(template_df)
    names = set(template_df["template_name"].apply(clean_cell).tolist())

    no_to_name: Dict[str, str] = {}
    for _, row in template_df.iterrows():
        template_no = normalize_template_key(row.get("template_no", ""))
        template_name = clean_cell(row.get("template_name", ""))
        if not template_no or not template_name:
            continue
        if template_no in no_to_name and no_to_name[template_no] != template_name:
            raise ValueError(
                f"Duplicate template_no with different template_name in Ref__BundleTemplates: "
                f"template_no={template_no}, names={no_to_name[template_no]} / {template_name}"
            )
        no_to_name[template_no] = template_name

    return names, no_to_name


def resolve_template_name(
    row: pd.Series,
    template_names_in_ref: set[str],
    template_no_to_name: Dict[str, str],
) -> Tuple[str, str, str]:
    """
    Rule:
    - template_name and template_no can fill either one.
    - If both are filled and conflict, template_name wins.
    - If template_name is numeric-like and not a real template_name, treat it as template_no.
    Returns: resolved_template_name, template_no, resolution_note
    """
    sku = clean_cell(row.get("sku", ""))
    raw_template_no = normalize_template_key(row.get("template_no", ""))
    raw_template_name = clean_cell(row.get("template_name", ""))

    resolution_note = ""

    if raw_template_name and raw_template_name not in template_names_in_ref and is_numeric_like(raw_template_name):
        if not raw_template_no:
            raw_template_no = normalize_template_key(raw_template_name)
            raw_template_name = ""
            resolution_note = "template_name_numeric_treated_as_template_no"

    if raw_template_name:
        if raw_template_name not in template_names_in_ref:
            raise ValueError(f"template_name not found in Ref__BundleTemplates: {raw_template_name}")

        if raw_template_no:
            mapped_name = template_no_to_name.get(raw_template_no, "")
            if mapped_name and mapped_name != raw_template_name:
                resolution_note = (
                    f"template_no_conflict_ignored: template_no={raw_template_no} "
                    f"maps_to={mapped_name}, used_template_name={raw_template_name}"
                )
            elif mapped_name == raw_template_name:
                resolution_note = "template_no_and_template_name_matched"
            else:
                resolution_note = f"template_no_not_found_ignored: template_no={raw_template_no}"
        else:
            resolution_note = resolution_note or "template_name_only"

        return raw_template_name, raw_template_no, resolution_note

    if raw_template_no:
        mapped_name = template_no_to_name.get(raw_template_no, "")
        if not mapped_name:
            raise ValueError(f"template_no not found in Ref__BundleTemplates: {raw_template_no}")
        return mapped_name, raw_template_no, "template_no_only"

    raise ValueError(f"Both template_no and template_name are empty for sku={sku}")


def resolve_candidate_quantities_by_type(type_value: Any, quantities: Optional[List[int]] = None) -> List[int]:
    if quantities:
        return [int(q) for q in quantities]

    type_key = normalize_template_key(type_value)
    if not type_key:
        raise ValueError("Type is empty")
    if type_key not in TYPE_TO_QUANTITIES:
        raise ValueError(
            f"Unsupported Type={type_key}. Supported Type values: {sorted(TYPE_TO_QUANTITIES.keys())}"
        )
    return TYPE_TO_QUANTITIES[type_key]


# =========================
# Placement generation
# =========================

def make_placement(view: str, x: float, y: float, w: float, h: float, scale: float, fit: str) -> Placement:
    return Placement(view=view, x=x, y=y, w=w, h=h, scale=scale, fit=fit)


def placements_matrix(rule: LayoutRule) -> List[Placement]:
    if rule.count <= 0:
        return []

    width = rule.x2 - rule.x1
    height = rule.y2 - rule.y1
    cell_w = width / rule.cols
    cell_h = height / rule.rows

    placements: List[Placement] = []
    for i in range(rule.count):
        r = i // rule.cols
        c = i % rule.cols
        if r >= rule.rows:
            break
        x = rule.x1 + cell_w * (c + 0.5)
        y = rule.y1 + cell_h * (r + 0.5)
        placements.append(
            make_placement(
                view=rule.view,
                x=x,
                y=y,
                w=cell_w,
                h=cell_h,
                scale=rule.scale,
                fit=rule.fit,
            )
        )
    return placements


def placements_center(rule: LayoutRule) -> List[Placement]:
    x = (rule.x1 + rule.x2) / 2
    y = (rule.y1 + rule.y2) / 2
    w = rule.x2 - rule.x1
    h = rule.y2 - rule.y1
    return [make_placement(rule.view, x, y, w, h, rule.scale, rule.fit) for _ in range(max(1, rule.count))]


def placements_vertical(rule: LayoutRule) -> List[Placement]:
    # Vertical means count items top-to-bottom in one column unless rows/cols explicitly define another matrix.
    cols = max(1, rule.cols)
    rows = max(rule.rows, (rule.count + cols - 1) // cols)
    proxy = LayoutRule(**{**rule.__dict__, "rows": rows, "cols": cols})
    return placements_matrix(proxy)


def placements_horizontal(rule: LayoutRule) -> List[Placement]:
    # Horizontal means count items left-to-right in one row unless rows/cols explicitly define another matrix.
    rows = max(1, rule.rows)
    cols = max(rule.cols, (rule.count + rows - 1) // rows)
    proxy = LayoutRule(**{**rule.__dict__, "rows": rows, "cols": cols})
    return placements_matrix(proxy)


def placements_diagonal(rule: LayoutRule) -> List[Placement]:
    if rule.count <= 0:
        return []

    # If only one item, place it slightly according to role implication but still centered in its box.
    if rule.count == 1:
        return placements_center(rule)

    width = rule.x2 - rule.x1
    height = rule.y2 - rule.y1
    w = width / max(1.25, min(2.0, rule.count))
    h = height / max(1.25, min(2.0, rule.count))

    placements: List[Placement] = []
    for i in range(rule.count):
        t = i / max(1, rule.count - 1)
        x = rule.x1 + width * (0.30 + 0.40 * t)
        y = rule.y1 + height * (0.30 + 0.40 * t)
        placements.append(make_placement(rule.view, x, y, w, h, rule.scale, rule.fit))
    return placements


def placements_pyramid(rule: LayoutRule) -> List[Placement]:
    if rule.count <= 0:
        return []

    # Supported practical patterns:
    # 3 -> 1 + 2
    # 5 -> 1 + 2 + 2
    # Otherwise use matrix fallback.
    width = rule.x2 - rule.x1
    height = rule.y2 - rule.y1

    if rule.count == 3:
        points = [
            (0.50, 0.28),
            (0.34, 0.68),
            (0.66, 0.68),
        ]
        w = width * 0.46
        h = height * 0.38
    elif rule.count == 5:
        points = [
            (0.50, 0.18),
            (0.34, 0.48),
            (0.66, 0.48),
            (0.34, 0.78),
            (0.66, 0.78),
        ]
        w = width * 0.42
        h = height * 0.30
    else:
        return placements_matrix(rule)

    return [
        make_placement(
            rule.view,
            rule.x1 + width * px,
            rule.y1 + height * py,
            w,
            h,
            rule.scale,
            rule.fit,
        )
        for px, py in points[: rule.count]
    ]


def placements_for_rule(rule: LayoutRule) -> List[Placement]:
    pattern = rule.pattern
    if pattern == "center" or pattern == "manual":
        return placements_center(rule)
    if pattern == "matrix":
        return placements_matrix(rule)
    if pattern == "vertical":
        return placements_vertical(rule)
    if pattern == "horizontal":
        return placements_horizontal(rule)
    if pattern == "diagonal":
        return placements_diagonal(rule)
    if pattern == "pyramid":
        return placements_pyramid(rule)
    raise ValueError(f"Unsupported pattern: {pattern}")


# =========================
# Render
# =========================

def render_quantity_image(
    view_images: Dict[str, Image.Image],
    layout_rules: List[LayoutRule],
    canvas_size: int = 1500,
    background_rgb: Tuple[int, int, int] = (255, 255, 255),
    scale_config: Optional[Dict[str, Any]] = None,
    template_name: str = "",
) -> Image.Image:
    canvas = Image.new("RGBA", (canvas_size, canvas_size), background_rgb + (255,))

    render_scale = float(get_global_scale_value(scale_config, "render_scale", 1.0))
    template_scale = get_template_scale(template_name, scale_config) if template_name else 1.0

    placements: List[Placement] = []
    for rule in sorted(layout_rules, key=lambda r: r.z_index):
        placements.extend(placements_for_rule(rule))

    for item in placements:
        view = item.view
        if view not in view_images:
            view = "image"

        src = view_images[view]

        target_w = max(1, int(canvas_size * item.w * item.scale * render_scale * template_scale))
        target_h = max(1, int(canvas_size * item.h * item.scale * render_scale * template_scale))

        fitted = fit_image(src, target_w, target_h, fit=item.fit)

        cx = int(canvas_size * item.x)
        cy = int(canvas_size * item.y)
        paste_center(canvas, fitted, cx, cy)

    return canvas.convert("RGB")


# =========================
# Main generation
# =========================

def generate_from_dataframes(
    input_df: pd.DataFrame,
    template_df: pd.DataFrame,
    layout_df: pd.DataFrame,
    output_dir: str | Path,
    cache_dir: str | Path,
    sprite_dir: Optional[str | Path] = None,
    save_sprite_images: bool = False,
    quantities: Optional[List[int]] = None,
    canvas_size: int = 1500,
    output_format: str = "jpg",
    overwrite: bool = True,
    remove_bg: bool = True,
    white_threshold: int = 246,
    scale_config: Optional[Dict[str, Any]] = None,
) -> pd.DataFrame:
    input_df = normalize_input_df(input_df)
    template_df = normalize_template_df(template_df)

    output_dir = ensure_dir(output_dir)
    cache_dir = ensure_dir(cache_dir)
    sprite_dir_path = ensure_dir(sprite_dir) if sprite_dir else None

    layout_map = build_layout_map(layout_df)
    template_names_in_ref, template_no_to_name = build_template_ref_maps(template_df)

    runlog: List[Dict[str, Any]] = []

    for idx, row in input_df.iterrows():
        sku = clean_cell(row.get("sku", ""))
        output_name = clean_cell(row.get("output_name", "")) or f"{sku}-SPU"
        type_value = clean_cell(row.get("Type", ""))
        raw_template_no = clean_cell(row.get("template_no", ""))
        raw_template_name = clean_cell(row.get("template_name", ""))

        resolved_template_name = raw_template_name
        template_resolution_note = ""
        candidate_quantities: List[int] = []
        actual_quantities: List[int] = []

        started = time.time()

        try:
            resolved_template_name, resolved_template_no, template_resolution_note = resolve_template_name(
                row=row,
                template_names_in_ref=template_names_in_ref,
                template_no_to_name=template_no_to_name,
            )

            candidate_quantities = resolve_candidate_quantities_by_type(type_value, quantities=quantities)
            actual_quantities = [
                q for q in candidate_quantities if (resolved_template_name, q) in layout_map
            ]
            skipped_quantities = [
                q for q in candidate_quantities if (resolved_template_name, q) not in layout_map
            ]

            if not actual_quantities:
                raise ValueError(
                    f"No matching layout quantities for template={resolved_template_name}. "
                    f"Candidate quantities={candidate_quantities}. "
                    f"Check Ref__BundleTemplateLayouts."
                )

            url_map = resolve_url_map(row)
            view_images, source_paths, sprite_paths = build_view_images(
                url_map=url_map,
                cache_dir=cache_dir,
                remove_bg=remove_bg,
                white_threshold=white_threshold,
                scale_config=scale_config,
                sku=sku,
                sprite_dir=sprite_dir_path,
                save_sprite_images=save_sprite_images,
            )

            unique_source_urls = set(url_map.values())
            source_count = len(unique_source_urls)

            # Log skipped missing layout quantities, but do not fail.
            for qty in skipped_quantities:
                runlog.append({
                    "ts": pd.Timestamp.utcnow().isoformat(),
                    "sku": sku,
                    "Type": type_value,
                    "output_name": output_name,
                    "template_no_input": raw_template_no,
                    "template_name_input": raw_template_name,
                    "template_name": resolved_template_name,
                    "template_resolution_note": template_resolution_note,
                    "quantity": qty,
                    "status": "skipped_no_layout",
                    "output_path": "",
                    "source_count": source_count,
                    "image_url": url_map.get("image", ""),
                    "front_url": url_map.get("front", ""),
                    "angle_url": url_map.get("angle", ""),
                    "side_url": url_map.get("side", ""),
                    "sprite_image_path": sprite_paths.get("image", ""),
                    "sprite_front_path": sprite_paths.get("front", ""),
                    "sprite_angle_path": sprite_paths.get("angle", ""),
                    "sprite_side_path": sprite_paths.get("side", ""),
                    "message": f"No layout for template={resolved_template_name}, quantity={qty}",
                    "elapsed_sec": round(time.time() - started, 2),
                })

            for qty in actual_quantities:
                out_ext = "jpg" if output_format.lower() in ["jpg", "jpeg"] else "png"
                filename = f"{safe_filename(output_name)}_{qty}pcs.{out_ext}"
                out_path = output_dir / filename

                if out_path.exists() and not overwrite:
                    status = "skipped_exists"
                else:
                    img = render_quantity_image(
                        view_images=view_images,
                        layout_rules=layout_map[(resolved_template_name, qty)],
                        canvas_size=canvas_size,
                        scale_config=scale_config,
                        template_name=resolved_template_name,
                    )
                    if out_ext == "jpg":
                        img.save(out_path, quality=95, optimize=True)
                    else:
                        img.save(out_path)
                    status = "success"

                runlog.append({
                    "ts": pd.Timestamp.utcnow().isoformat(),
                    "sku": sku,
                    "Type": type_value,
                    "output_name": output_name,
                    "template_no_input": raw_template_no,
                    "template_name_input": raw_template_name,
                    "template_name": resolved_template_name,
                    "template_resolution_note": template_resolution_note,
                    "quantity": qty,
                    "status": status,
                    "output_path": str(out_path),
                    "source_count": source_count,
                    "image_url": url_map.get("image", ""),
                    "front_url": url_map.get("front", ""),
                    "angle_url": url_map.get("angle", ""),
                    "side_url": url_map.get("side", ""),
                    "sprite_image_path": sprite_paths.get("image", ""),
                    "sprite_front_path": sprite_paths.get("front", ""),
                    "sprite_angle_path": sprite_paths.get("angle", ""),
                    "sprite_side_path": sprite_paths.get("side", ""),
                    "message": "",
                    "elapsed_sec": round(time.time() - started, 2),
                })

        except Exception as e:
            runlog.append({
                "ts": pd.Timestamp.utcnow().isoformat(),
                "sku": sku,
                "Type": type_value,
                "output_name": output_name,
                "template_no_input": raw_template_no,
                "template_name_input": raw_template_name,
                "template_name": resolved_template_name,
                "template_resolution_note": template_resolution_note,
                "quantity": ",".join(str(x) for x in candidate_quantities) if candidate_quantities else "",
                "status": "error",
                "output_path": "",
                "source_count": "",
                "image_url": clean_cell(row.get("image_url", "")),
                "front_url": clean_cell(row.get("front_url", "")),
                "angle_url": clean_cell(row.get("angle_url", "")),
                "side_url": clean_cell(row.get("side_url", "")),
                "sprite_image_path": "",
                "sprite_front_path": "",
                "sprite_angle_path": "",
                "sprite_side_path": "",
                "message": str(e),
                "elapsed_sec": round(time.time() - started, 2),
            })

    log_df = pd.DataFrame(runlog)
    log_path = output_dir / "bundle_image_runlog.csv"
    log_df.to_csv(log_path, index=False)

    return log_df


def generate_from_google_sheet(
    sheet_url: str,
    service_account_json_or_b64: str,
    input_tab: str,
    template_tab: str,
    layout_tab: str,
    output_dir: str | Path,
    cache_dir: str | Path,
    sprite_dir: Optional[str | Path] = None,
    save_sprite_images: bool = False,
    quantities: Optional[List[int]] = None,
    canvas_size: int = 1500,
    output_format: str = "jpg",
    overwrite: bool = True,
    remove_bg: bool = True,
    white_threshold: int = 246,
    scale_config: Optional[Dict[str, Any]] = None,
) -> pd.DataFrame:
    input_df, template_df, layout_df = read_google_sheet_tabs(
        sheet_url=sheet_url,
        service_account_json_or_b64=service_account_json_or_b64,
        input_tab=input_tab,
        template_tab=template_tab,
        layout_tab=layout_tab,
    )

    return generate_from_dataframes(
        input_df=input_df,
        template_df=template_df,
        layout_df=layout_df,
        output_dir=output_dir,
        cache_dir=cache_dir,
        sprite_dir=sprite_dir,
        save_sprite_images=save_sprite_images,
        quantities=quantities,
        canvas_size=canvas_size,
        output_format=output_format,
        overwrite=overwrite,
        remove_bg=remove_bg,
        white_threshold=white_threshold,
        scale_config=scale_config,
    )
